version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: zenodo
    main: ./cmd/zenodo
    binary: zenodo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/ran-codes/zenodo-cli/internal/cli.version={{.Version}}
      - -X github.com/ran-codes/zenodo-cli/internal/cli.commit={{.Commit}}
      - -X github.com/ran-codes/zenodo-cli/internal/cli.date={{.Date}}

  - id: zenodo-mcp
    main: ./cmd/zenodo-mcp
    binary: zenodo-mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
